services:
  vouchers-app:
    container_name: vouchers-facilpass-prod
    build:
      context: .
      dockerfile: Dockerfile
    image: vouchers-app:prod
    networks:
      - proxy-network
    labels:
      - traefik.docker.network=proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
